# Generated by Django 5.2.14 on 2026-05-28 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('cpp', 'C++'), ('c', 'C'), ('sql', 'SQL'), ('html', 'HTML'), ('css', 'CSS')], default='python', max_length=20, verbose_name='Til')),
                ('starter_code', models.TextField(blank=True, verbose_name="Boshlang'ich kod")),
                ('solution_code', models.TextField(blank=True, verbose_name='Yechim kodi')),
                ('difficulty', models.CharField(choices=[('easy', 'Oson'), ('medium', "O'rta"), ('hard', 'Qiyin')], default='easy', max_length=20, verbose_name='Qiyinlik')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': "Kod topshirig'i",
                'verbose_name_plural': 'Kod topshiriqlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Mening kodum', max_length=200, verbose_name='Sarlavha')),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('cpp', 'C++'), ('c', 'C'), ('sql', 'SQL'), ('html', 'HTML'), ('css', 'CSS')], default='python', max_length=20, verbose_name='Dasturlash tili')),
                ('code', models.TextField(verbose_name='Kod')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('submitted', 'Topshirildi')], default='draft', max_length=20, verbose_name='Holat')),
                ('is_public', models.BooleanField(default=False, verbose_name='Ommaviy')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='code_editor.codechallenge', verbose_name='Topshiriq')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Kod topshirmasi',
                'verbose_name_plural': 'Kod topshirmalari',
                'ordering': ['-created_at'],
            },
        ),
    ]
